In [5]:
# Exercise 1: 

import numpy as np

# Create a numpy array containing numbers from 1 to 10
array = np.arange(1, 11)
print(array)

# Reshape the array to a 2x5 matrix
reshaped_array = array.reshape(2, 5)

print(reshaped_array)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# Exercise 2:

# Create a numpy array containing numbers from 1 to 20
array = np.arange(1, 21)
print(array)

# Extract the elements between the 5th and 15th index
extracted_elements = array[5:16]

print(extracted_elements)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [12]:
# Exercise 3:

import pandas as pd

# Create a Pandas Series with the given data
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add a new item to the Series
fruit_series['pears'] = 4

# Print the updated Series
print(fruit_series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [24]:
# Exercise 4:

# Create a dictionary with sample data
data = {
    'name': ['Aleena', 'Binu', 'Chethan', 'Dino', 'Elsa', 'Firoz', 'Geetha', 'Hima', 'Isac', 'Jelmy'],
    'age': [25, 30, 22, 35, 28, 40, 32, 27, 24, 29],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
print(df)


      name  age  gender
0   Aleena   25  Female
1     Binu   30    Male
2  Chethan   22    Male
3     Dino   35    Male
4     Elsa   28  Female
5    Firoz   40    Male
6   Geetha   32  Female
7     Hima   27  Female
8     Isac   24    Male
9    Jelmy   29  Female


In [26]:
# Exercise 5:
# Add a new column called 'occupation' to the DataFrame
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

# Print the updated DataFrame
print(df)




      name  age  gender  occupation
0   Aleena   25  Female  Programmer
1     Binu   30    Male     Manager
2  Chethan   22    Male     Analyst
3     Dino   35    Male  Programmer
4     Elsa   28  Female     Manager
5    Firoz   40    Male     Analyst
6   Geetha   32  Female  Programmer
7     Hima   27  Female     Manager
8     Isac   24    Male     Analyst
9    Jelmy   29  Female  Programmer


In [27]:
# Exercise 6: 
# Filter rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]

# Print the filtered DataFrame
print(filtered_df)


     name  age  gender  occupation
1    Binu   30    Male     Manager
3    Dino   35    Male  Programmer
5   Firoz   40    Male     Analyst
6  Geetha   32  Female  Programmer


In [31]:
# Exercise 7:

df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('sample_data.csv', index=False)

# Read the CSV file into a DataFrame
df_from_csv = pd.read_csv('sample_data.csv')

# Display the contents of the DataFrame
print(df_from_csv)


      name  age  gender
0   Aleena   25  Female
1     Binu   30    Male
2  Chethan   22    Male
3     Dino   35    Male
4     Elsa   28  Female
5    Firoz   40    Male
6   Geetha   32  Female
7     Hima   27  Female
8     Isac   24    Male
9    Jelmy   29  Female
